[hycov]
description = "hyprland overview mode"
version = "0.1"
author = "DreamMaoMao"

[hycov.build]
output = "build/libhycov.so"
steps = [
  "cmake -DCMAKE_BUILD_TYPE=Debug -B build",
  "cmake --build build"
]
